version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/raspberrypi4-homeassistant:stable
    volumes:
      - /home/pi/homeassistant:/config
    environment:
      - TZ=Europe/Warsaw
    restart: always
    network_mode: host
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
